/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzeComplexity(prompt: string, agentType?: string | undefined | null): JsComplexityAnalysis

export declare function createHookOutputDeny(reason: string): JsHookOutput

export declare function createHookOutputStop(reason: string): JsHookOutput

export declare function createHookOutputWithMessage(message: string): JsHookOutput

export declare function detectAllKeywords(prompt: string, agent?: string | undefined | null): Array<DetectedKeyword>

export interface DetectedKeyword {
  keywordType: string
  message: string
}

export declare function detectKeywords(prompt: string, agent?: string | undefined | null): JsHookOutput | null

/**
 * Execute hooks for a specific event
 *
 * # Arguments
 * * `event` - Event type: "user-prompt-submit", "stop", "session-start", "pre-tool-use", "post-tool-use", "session-idle", "messages-transform"
 * * `input` - Hook input data
 *
 * # Returns
 * Hook output with continue flag, message, etc.
 */
export declare function executeHook(event: string, input: JsHookInput): Promise<JsHookOutput>

/**
 * Get a specific agent by name
 *
 * # Arguments
 * * `name` - Agent name (e.g., "architect", "executor-high", "explore")
 *
 * # Returns
 * Agent definition if found, None otherwise
 */
export declare function getAgent(name: string): JsAgentDefinition | null

/** Get the number of registered hooks */
export declare function getHookCount(): number

/**
 * Get a skill by name
 *
 * Loads skill from SKILL.md files in the skills/ directory.
 *
 * # Arguments
 * * `name` - Skill name (e.g., "autopilot", "ralph", "ultrawork")
 *
 * # Returns
 * Skill template content if found, None otherwise
 */
export declare function getSkill(name: string): string | null

/**
 * Get full skill definition
 *
 * # Arguments
 * * `name` - Skill name
 *
 * # Returns
 * Full skill definition with metadata
 */
export declare function getSkillDefinition(name: string): JsSkillDefinition | null

/** Agent definition exposed to JavaScript */
export interface JsAgentDefinition {
  name: string
  description: string
  model?: string
  tier: string
  prompt: string
  tools: Array<string>
}

/**
 * Analyze task complexity
 *
 * Provides detailed complexity analysis for a task prompt.
 *
 * # Arguments
 * * `prompt` - The task prompt to analyze
 * * `agent_type` - Optional agent type for context
 *
 * # Returns
 * Analysis result with tier, model, and detailed breakdown
 */
export interface JsComplexityAnalysis {
  tier: string
  model: string
  analysis: string
}

/** Input for hook execution from JavaScript */
export interface JsHookInput {
  sessionId?: string
  prompt?: string
  toolName?: string
  toolInput?: string
  toolOutput?: string
  directory?: string
  stopReason?: string
  userRequested?: boolean
}

export interface JsHookOutput {
  continue: boolean
  message?: string
  stopReason?: string
  decision?: string
  reason?: string
  additionalContext?: string
  suppressOutput?: boolean
  systemMessage?: string
}

/** Result of model routing decision */
export interface JsRoutingResult {
  model: string
  tier: string
  reasoning: string
  confidence: number
  escalated: boolean
}

/** Skill definition exposed to JavaScript */
export interface JsSkillDefinition {
  name: string
  description: string
  template: string
  agent?: string
  model?: string
  argumentHint?: string
}

/** Get list of agent names only (lighter weight than full definitions) */
export declare function listAgentNames(): Array<string>

/**
 * List all available agent definitions
 *
 * Returns all 32 agent definitions from astrape-agents including:
 * - Primary agents (architect, executor, explore, etc.)
 * - Tiered variants (architect-low, architect-medium, executor-high, etc.)
 * - Specialized agents (security-reviewer, build-fixer, etc.)
 */
export declare function listAgents(): Array<JsAgentDefinition>

/** List all registered hooks */
export declare function listHooks(): Array<string>

/**
 * List all available skill names
 *
 * # Returns
 * List of skill names loaded from the skills/ directory
 */
export declare function listSkills(): Array<string>

/**
 * Route a task to the appropriate model tier
 *
 * Uses complexity analysis to determine the best model for a given task.
 * Considers lexical signals, structural complexity, and context.
 *
 * # Arguments
 * * `prompt` - The task prompt to analyze
 *
 * # Returns
 * Routing result with model, tier, and reasoning
 */
export declare function routeTaskPrompt(prompt: string): JsRoutingResult

/**
 * Route a task with agent context
 *
 * # Arguments
 * * `prompt` - The task prompt to analyze
 * * `agent_type` - Optional agent type (e.g., "architect", "explore")
 *
 * # Returns
 * Routing result with model, tier, and reasoning
 */
export declare function routeTaskWithAgent(prompt: string, agentType?: string | undefined | null): JsRoutingResult

// ============================================================================
// Background Task Notification Bindings
// ============================================================================

/** Result of checking for background notifications */
export interface JsNotificationResult {
  hasNotifications: boolean
  message?: string
  notificationCount: number
}

/**
 * Check for pending background task notifications for a session
 *
 * # Arguments
 * * `sessionId` - The session ID to check notifications for
 *
 * # Returns
 * Notification result with message if notifications are pending
 */
export declare function checkNotifications(sessionId: string): JsNotificationResult

/**
 * Process a background task event (task.completed or task.failed)
 *
 * # Arguments
 * * `eventJson` - JSON string with event type and properties
 */
export declare function notifyBackgroundEvent(eventJson: string): void

/**
 * Register a background task for tracking
 *
 * # Arguments
 * * `taskId` - Unique task identifier
 * * `sessionId` - Child session ID
 * * `parentSessionId` - Parent session ID to notify
 * * `description` - Task description
 * * `agent` - Agent name running the task
 */
export declare function registerBackgroundTask(
  taskId: string,
  sessionId: string,
  parentSessionId: string,
  description: string,
  agent: string
): void
